export const booksData = [
    {
        "id": 1,
        "title": "Essence Mascara Lash Princess",
        "category": "beauty",
        "price": 9.99,
        "discount Percentage": 10.48,
        "rating": 2.56,
        "stock": 99,
        "brand": "Essence",
        "sku": "BEA-ESS-ESS-001",
        "weight": 4,
        "warranty Information": "1 week warranty",
        "shipping Information": "Ships in 3-5 business days"
    }, {
        "id": 2,
        "title": "Eyeshadow Palette with Mirror",
        "category": "beauty",
        "price": 19.99,
        "discount Percentage": 18.19,
        "rating": 2.86,
        "stock": 34,
        "brand": "Glamour Beauty",
        "sku": "BEA-GLA-EYE-002",
        "weight": 9,
        "warranty Information": "1 year warranty",
        "shipping Information": "Ships in 2 weeks"
    }, {
        "id": 3,
        "title": "Powder Canister",
        "category": "beauty",
        "price": 14.99,
        "discount Percentage": 9.84,
        "rating": 4.64,
        "stock": 89,
        "brand": "Velvet Touch",
        "sku": "BEA-VEL-POW-003",
        "weight": 8,
        "warranty Information": "3 months warranty",
        "shipping Information": "Ships in 1-2 business days"
    }, {
        "id": 4,
        "title": "Red Lipstick",
        "category": "beauty",
        "price": 12.99,
        "discount Percentage": 12.16,
        "rating": 4.36,
        "stock": 91,
        "brand": "Chic Cosmetics",
        "sku": "BEA-CHI-LIP-004",
        "weight": 1,
        "warranty Information": "3 year warranty",
        "shipping Information": "Ships in 1 week"
    }, {
        "id": 5,
        "title": "Red Nail Polish",
        "category": "beauty",
        "price": 8.99,
        "discount Percentage": 11.44,
        "rating": 4.32,
        "stock": 79,
        "brand": "Nail Couture",
        "sku": "BEA-NAI-NAI-005",
        "weight": 8,
        "warranty Information": "1 month warranty",
        "shipping Information": "Ships overnight"
    }, {
        "id": 6,
        "title": "Calvin Klein CK One",
        "category": "fragrances",
        "price": 49.99,
        "discount Percentage": 1.89,
        "rating": 4.37,
        "stock": 29,
        "brand": "Calvin Klein",
        "sku": "FRA-CAL-CAL-006",
        "weight": 7,
        "warranty Information": "1 week warranty",
        "shipping Information": "Ships overnight"
    }, {
        "id": 7,
        "title": "Chanel Coco Noir Eau De",
        "category": "fragrances",
        "price": 129.99,
        "discount Percentage": 16.51,
        "rating": 4.26,
        "stock": 58,
        "brand": "Chanel",
        "sku": "FRA-CHA-CHA-007",
        "weight": 7,
        "warranty Information": "3 year warranty",
        "shipping Information": "Ships overnight"
    }, {
        "id": 8,
        "title": "Dior J'adore",
        "category": "fragrances",
        "price": 89.99,
        "discount Percentage": 14.72,
        "rating": 3.8,
        "stock": 98,
        "brand": "Dior",
        "sku": "FRA-DIO-DIO-008",
        "weight": 4,
        "warranty Information": "1 week warranty",
        "shipping Information": "Ships in 2 weeks"
    }, {
        "id": 9,
        "title": "Dolce Shine Eau de",
        "category": "fragrances",
        "price": 69.99,
        "discount Percentage": 0.62,
        "rating": 3.96,
        "stock": 4,
        "brand": "Dolce & Gabbana",
        "sku": "FRA-DOL-DOL-009",
        "weight": 6,
        "warranty Information": "3 year warranty",
        "shipping Information": "Ships in 1 month"
    }, {
        "id": 10,
        "title": "Gucci Bloom Eau de",
        "category": "fragrances",
        "price": 79.99,
        "discount Percentage": 14.39,
        "rating": 2.74,
        "stock": 91,
        "brand": "Gucci",
        "sku": "FRA-GUC-GUC-010",
        "weight": 7,
        "warranty Information": "6 months warranty",
        "shipping Information": "Ships overnight"
    }, {
        "id": 11,
        "title": "Annibale Colombo Bed",
        "category": "furniture",
        "price": 1899.99,
        "discount Percentage": 8.57,
        "rating": 4.77,
        "stock": 88,
        "brand": "Annibale Colombo",
        "sku": "FUR-ANN-ANN-011",
        "weight": 10,
        "warranty Information": "1 year warranty",
        "shipping Information": "Ships in 1 month"
    }, {
        "id": 12,
        "title": "Annibale Colombo Sofa",
        "category": "furniture",
        "price": 2499.99,
        "discount Percentage": 14.4,
        "rating": 3.92,
        "stock": 60,
        "brand": "Annibale Colombo",
        "sku": "FUR-ANN-ANN-012",
        "weight": 6,
        "warranty Information": "Lifetime warranty",
        "shipping Information": "Ships in 1 week"
    }, {
        "id": 13,
        "title": "Bedside Table African Cherry",
        "category": "furniture",
        "price": 299.99,
        "discount Percentage": 19.09,
        "rating": 2.87,
        "stock": 64,
        "brand": "Furniture Co.",
        "sku": "FUR-FUR-BED-013",
        "weight": 2,
        "warranty Information": "5 year warranty",
        "shipping Information": "Ships overnight"
    }, {
        "id": 14,
        "title": "Knoll Saarinen Executive Conference Chair",
        "category": "furniture",
        "price": 499.99,
        "discount Percentage": 2.01,
        "rating": 4.88,
        "stock": 26,
        "brand": "Knoll",
        "sku": "FUR-KNO-KNO-014",
        "weight": 10,
        "warranty Information": "2 year warranty",
        "shipping Information": "Ships overnight"
    }, {
        "id": 15,
        "title": "Wooden Bathroom Sink With Mirror",
        "category": "furniture",
        "price": 799.99,
        "discount Percentage": 8.8,
        "rating": 3.59,
        "stock": 7,
        "brand": "Bath Trends",
        "sku": "FUR-BAT-WOO-015",
        "weight": 10,
        "warranty Information": "3 year warranty",
        "shipping Information": "Ships in 3-5 business days"
    }, {
        "id": 16,
        "title": "Apple",
        "category": "groceries",
        "price": 1.99,
        "discount Percentage": 12.62,
        "rating": 4.19,
        "stock": 8,
        "sku": "GRO-BRD-APP-016",
        "weight": 9,
        "warranty Information": "3 year warranty",
        "shipping Information": "Ships in 2 weeks"
    }, {
        "id": 17,
        "title": "Beef Steak",
        "category": "groceries",
        "price": 12.99,
        "discount Percentage": 9.61,
        "rating": 4.47,
        "stock": 86,
        "sku": "GRO-BRD-BEE-017",
        "weight": 10,
        "warranty Information": "3 year warranty",
        "shipping Information": "Ships overnight"
    }, {
        "id": 18,
        "title": "Cat Food",
        "category": "groceries",
        "price": 8.99,
        "discount Percentage": 9.58,
        "rating": 3.13,
        "stock": 46,
        "sku": "GRO-BRD-FOO-018",
        "weight": 10,
        "warranty Information": "1 year warranty",
        "shipping Information": "Ships overnight"
    }, {
        "id": 19,
        "title": "Chicken Meat",
        "category": "groceries",
        "price": 9.99,
        "discount Percentage": 13.7,
        "rating": 3.19,
        "stock": 97,
        "sku": "GRO-BRD-CHI-019",
        "weight": 1,
        "warranty Information": "1 year warranty",
        "shipping Information": "Ships in 1 month"
    }, {
        "id": 20,
        "title": "Cooking Oil",
        "category": "groceries",
        "price": 4.99,
        "discount Percentage": 9.33,
        "rating": 4.8,
        "stock": 10,
        "sku": "GRO-BRD-COO-020",
        "weight": 5,
        "warranty Information": "Lifetime warranty",
        "shipping Information": "Ships in 1-2 business days"
    }, {
        "id": 21,
        "title": "Cucumber",
        "category": "groceries",
        "price": 1.49,
        "discount Percentage": 0.16,
        "rating": 4.07,
        "stock": 84,
        "sku": "GRO-BRD-CUC-021",
        "weight": 4,
        "warranty Information": "2 year warranty",
        "shipping Information": "Ships in 1-2 business days"
    }, {
        "id": 22,
        "title": "Dog Food",
        "category": "groceries",
        "price": 10.99,
        "discount Percentage": 10.27,
        "rating": 4.55,
        "stock": 71,
        "sku": "GRO-BRD-FOO-022",
        "weight": 10,
        "warranty Information": "No warranty",
        "shipping Information": "Ships in 1-2 business days"
    }, {
        "id": 23,
        "title": "Eggs",
        "category": "groceries",
        "price": 2.99,
        "discount Percentage": 11.05,
        "rating": 2.53,
        "stock": 9,
        "sku": "GRO-BRD-EGG-023",
        "weight": 2,
        "warranty Information": "1 week warranty",
        "shipping Information": "Ships in 1 week"
    }, {
        "id": 24,
        "title": "Fish Steak",
        "category": "groceries",
        "price": 14.99,
        "discount Percentage": 4.23,
        "rating": 3.78,
        "stock": 74,
        "sku": "GRO-BRD-FIS-024",
        "weight": 6,
        "warranty Information": "1 month warranty",
        "shipping Information": "Ships in 3-5 business days"
    }, {
        "id": 25,
        "title": "Green Bell Pepper",
        "category": "groceries",
        "price": 1.29,
        "discount Percentage": 0.16,
        "rating": 3.25,
        "stock": 33,
        "sku": "GRO-BRD-GRE-025",
        "weight": 2,
        "warranty Information": "1 month warranty",
        "shipping Information": "Ships in 1 week"
    }, {
        "id": 26,
        "title": "Green Chili Pepper",
        "category": "groceries",
        "price": 0.99,
        "discount Percentage": 1,
        "rating": 3.66,
        "stock": 3,
        "sku": "GRO-BRD-GRE-026",
        "weight": 7,
        "warranty Information": "2 year warranty",
        "shipping Information": "Ships in 1 week"
    }, {
        "id": 27,
        "title": "Honey Jar",
        "category": "groceries",
        "price": 6.99,
        "discount Percentage": 14.4,
        "rating": 3.97,
        "stock": 34,
        "sku": "GRO-BRD-HON-027",
        "weight": 2,
        "warranty Information": "1 month warranty",
        "shipping Information": "Ships in 1-2 business days"
    }, {
        "id": 28,
        "title": "Ice Cream",
        "category": "groceries",
        "price": 5.49,
        "discount Percentage": 8.69,
        "rating": 3.39,
        "stock": 27,
        "sku": "GRO-BRD-CRE-028",
        "weight": 1,
        "warranty Information": "1 month warranty",
        "shipping Information": "Ships in 2 weeks"
    }, {
        "id": 29,
        "title": "Juice",
        "category": "groceries",
        "price": 3.99,
        "discount Percentage": 12.06,
        "rating": 3.94,
        "stock": 50,
        "sku": "GRO-BRD-JUI-029",
        "weight": 1,
        "warranty Information": "6 months warranty",
        "shipping Information": "Ships in 1 week"
    }, {
        "id": 30,
        "title": "Kiwi",
        "category": "groceries",
        "price": 2.49,
        "discount Percentage": 15.22,
        "rating": 4.93,
        "stock": 99,
        "sku": "GRO-BRD-KIW-030",
        "weight": 5,
        "warranty Information": "6 months warranty",
        "shipping Information": "Ships overnight"
    }
]