export const Button_Column_Width = "100px";
export const Fallback_Column_Width = "150px";
export const Maximum_Column_Width = 2400; // in pixels, also configured in CSS for td and th
export const Minimum_Column_Width = 75;  // in pixels, also configured in CSS for td and th
export const Container_Identifier = ".react-data-grid-lite";
export const No_Data_Message = "There is no data to display.";
export const No_Column_Visible_Message = "Column definitions may be missing or misconfigured, or all columns are currently hidden.";
export const CSV_File_Name_Prefix = "export";
export const Default_Grid_Width_VW = '90vw';
export const Button_Column_Key = 'ButtonColumnKey';
export const Export_To_CSV_Text = 'Export CSV';
export const Border_Padding_Margin_Width = "1";
export const Loader_Identifier = "table-loader-overlay";
export const Movement_Threshold = 10; // in pixels
export const Formatting_Types = ['date', 'number', 'currency', 'percent', 'boolean'];
export const OpenAI_API_EndPoint = 'https://api.openai.com/v1/chat/completions';
export const OpenAI_API_Model = 'gpt-4';
export const OpenAI_Default_System_Prompt = `You are a filtering assistant. Given a list of JSON rows, return only the rows matching the query. Only return a JSON array of matched rows.`;
export const Page_Size_Selector_Options = [5, 10, 25, 50, 100, 250, 500];