export const Mobile_Column_Width = "150px";
export const Button_Column_Width = "110px";
export const Fallback_Column_Width = "200px";
export const Maximum_Column_Width = 1200; // in pixels, also configured in CSS for td and th
export const Minimum_Column_Width = 100;  // in pixels, also configured in CSS for td and th
export const Container_Identifier = ".react-data-grid-lite";
export const No_Data_Message = "There is no data to display.";
export const No_Column_Visible_Message = "Column definitions may be missing or misconfigured, or all columns are currently hidden.";
export const CSV_File_Name_Prefix = "export";
export const Default_Grid_Width_VW = '90vw';
export const Button_Column_Key = 'ButtonColumnKey';
export const Export_To_CSV_Text = 'Export to CSV';
export const Border_Padding_Margin_Width = "6";
export const Loader_Identifier = "table-loader-overlay";